import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../../component/Sidebar";
import Header from "../../component/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex w-full max-w-full bg-slate-200`}
      >
        <div className="flex w-[200px] h-full fixed z-10">
          <Sidebar />
        </div>
        <div className="flex flex-col h-full w-4/5 ml-[200px]">
          <Header />
          <main className="flex w-full p-4 mt-16">{children}</main>
        </div>
      </body>
    </html>
  );
}
